apiVersion: v1
kind: Service
metadata:
  namespace: go-micro
  name: admin-srv
  labels:
    app: admin-srv
spec:
  type: NodePort
  ports:
    - port: 8080
      name: admin-srv-http
      nodePort: 30000
    - port: 9090
      name: admin-srv-grpc
      nodePort: 30001
  selector:
    app: admin-srv