kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: go-micro
  name: go-micro-config
  labels:
    app: go-micro-config
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "update", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: go-micro
  name: go-micro-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: go-micro-config
subjects:
  - kind: ServiceAccount
    namespace: go-micro
    name: go-micro-services
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: go-micro
  name: go-micro-services