apiVersion: v1
kind: Service
metadata:
  namespace: go-micro
  name: token-srv
  labels:
    app: token-srv
spec:
  ports:
    - port: 9090
      name: token-srv-grpc
      targetPort: 9090
  selector:
    app: token-srv