apiVersion: v1
kind: ConfigMap
metadata:
  namespace: go-micro
  name: user-srv
  labels:
    app: user-srv
data:
  config.yaml: |
    server:
      grpc:
        addr: 0.0.0.0:9090
        timeout: 1s

    registry:
      type: "k8s"