apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-micro
  name: user-srv
  labels:
    app: user-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-srv
  template:
    metadata:
      labels:
        app: user-srv
        gomicro-service-id: "56991810-0002-4a95-8190-393efa9c1a61"
        gomicro-service-app: "examples.k8s.user.srv"
        gomicro-service-version: "v1.0.0"
      annotations:
        gomicro-service-protocols: |
          {"9090": "grpc"}
        gomicro-service-metadata: |
          {"region": "sh", "zone": "sh001", "cluster": "pd"}
    spec:
      containers:
        - name: user-srv
          image: devexps/user-srv:k8s
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              name: grpc-port
      serviceAccountName: go-micro-services