server:
  grpc:
    addr: 0.0.0.0:9090
    timeout: 1s

registry:
  type: "consul"
  consul:
    address: 127.0.0.1:8500
    scheme: http
    health_check: false

auth:
  api_key: "some_api_key"

trace:
  endpoint: 127.0.0.1:6831