server:
  grpc:
    addr: 0.0.0.0:9092
    timeout: 1s

registry:
  type: "consul"
  consul:
    address: consul:8500
    scheme: http
    health_check: false

auth:
  api_key: "some_api_key"

trace:
  endpoint: jaeger:6831