server:
  http:
    addr: 0.0.0.0:8080
    timeout: 1s
    headers:
      - "Content-Type"
      - "Authorization"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "HEAD"
      - "OPTIONS"
    origins:
      - "*"
  grpc:
    addr: 0.0.0.0:9090
    timeout: 1s

client:
  grpc:
    timeout: 1s

registry:
  type: "consul"
  consul:
    address: consul:8500
    scheme: http
    health_check: false

trace:
  endpoint: jaeger:6831