server:
  grpc:
    addr: 0.0.0.0:9092
    timeout: 1s
    middleware:
      enable_recovery: true
      enable_tracing: true

registry:
  type: "consul"
  consul:
    address: 127.0.0.1:8500
    scheme: http
    health_check: false

trace:
  endpoint: 127.0.0.1:6831

data:
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 10s
    read_timeout: 0.2s
    write_timeout: 0.2s

auth:
  api_key: "some_api_key"