server:
  grpc:
    addr: 0.0.0.0:9091
    timeout: 1s
    middleware:
      enable_recovery: true
      enable_tracing: true

registry:
  type: "consul"
  consul:
    address: 127.0.0.1:8500
    scheme: http
    health_check: false

trace:
  endpoint: 127.0.0.1:6831

data:
  database:
    driver: "postgres"
    source: "host=localhost port=5432 user=micro password=micro@123 dbname=micro sslmode=disable"
    migrate: true