version: '3'
services:
  consul:
    image: docker.io/bitnami/consul:latest
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE='eth0'
      - CONSUL_AGENT_MODE=server
      - CONSUL_ENABLE_UI=true
      - CONSUL_BOOTSTRAP_EXPECT=1
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0