// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devexps/go-examples/micro-blog/api/gen/go/common/conf"
	"github.com/devexps/go-examples/micro-blog/token_service/internal/biz"
	"github.com/devexps/go-examples/micro-blog/token_service/internal/data"
	"github.com/devexps/go-examples/micro-blog/token_service/internal/server"
	"github.com/devexps/go-examples/micro-blog/token_service/internal/service"
	"github.com/devexps/go-micro/v2"
	"github.com/devexps/go-micro/v2/log"
	"github.com/devexps/go-micro/v2/registry"
)

// Injectors from wire.go:

// initApp init micro application.
func initApp(logger log.Logger, registrar registry.Registrar, bootstrap *conf.Bootstrap) (*micro.App, func(), error) {
	client := data.NewRedisClient(bootstrap, logger)
	dataData, cleanup, err := data.NewData(bootstrap, logger, client)
	if err != nil {
		return nil, nil, err
	}
	tokenRepo := data.NewTokenRepo(logger, dataData, bootstrap)
	tokenUseCase := biz.NewTokenUseCase(tokenRepo, logger)
	tokenService := service.NewTokenService(logger, tokenUseCase)
	grpcServer := server.NewGRPCServer(bootstrap, logger, tokenService)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
