// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devexps/go-examples/k8s/admin-srv/internal/data"
	"github.com/devexps/go-examples/k8s/admin-srv/internal/server"
	"github.com/devexps/go-examples/k8s/admin-srv/internal/service"
	"github.com/devexps/go-examples/k8s/api/gen/go/common/conf"
	"github.com/devexps/go-micro/v2"
	"github.com/devexps/go-micro/v2/log"
	"github.com/devexps/go-micro/v2/registry"
)

// Injectors from wire.go:

// initApp init micro application.
func initApp(logger log.Logger, registrar registry.Registrar, bootstrap *conf.Bootstrap) (*micro.App, func(), error) {
	discovery := data.NewDiscovery(bootstrap)
	userServiceClient := data.NewUserServiceClient(bootstrap, discovery)
	tokenServiceClient := data.NewTokenServiceClient(bootstrap, discovery)
	authenticationService := service.NewAuthenticationService(logger, userServiceClient, tokenServiceClient)
	httpServer := server.NewHTTPServer(bootstrap, logger, authenticationService)
	grpcServer := server.NewGRPCServer(bootstrap, logger, authenticationService)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
	}, nil
}
