version: '3'
services:
  consul:
    image: docker.io/bitnami/consul:latest
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE='eth0'
      - CONSUL_AGENT_MODE=server
      - CONSUL_ENABLE_UI=true
      - CONSUL_BOOTSTRAP_EXPECT=1
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0

  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

  postgres:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=micro
      - POSTGRES_PASSWORD=micro@123
      - POSTGRES_DB=micro

  redis:
    image: docker.io/bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes